FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

RUN apt-get update && \
    apt-get install -y nodejs && \
    apt-get install -y npm

WORKDIR /src
COPY ["react.test.WebApp/react.test.WebApp.csproj", "react.test.WebApp/"]
RUN dotnet restore "react.test.WebApp/react.test.WebApp.csproj"
COPY . .
WORKDIR "/src/react.test.WebApp"
RUN dotnet build "react.test.WebApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet build "react.test.WebApp.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "react.test.WebApp.dll"]