name: Publish image to Docker Hub
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t aphichatt/react.project:latest
      - name: publish
        run: |
          docker login -u aphichatt -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push aphichatt/react.project:latest
